import { LanguageTemplate } from "./types";

export const translations: Record<"en" | "hi", LanguageTemplate> = {
  en: {
    title: "MediaFire Auto-Bypass Downloader",
    subtitle: "Instantly resolve MediaFire links to direct, high-speed downloads with custom 3D acceleration.",
    pasteLabel: "Pasted MediaFire URL",
    placeholder: "Paste MediaFire link here (e.g., https://www.mediafire.com/file/...)",
    bypassBtn: "Bypass & Resolve",
    bypassing: "Bypassing Link...",
    speedMode: "Hyper 3D Engine",
    speedModeDesc: "Multi-threaded turbo engine with instant high-speed parallel routing.",
    instantDown: "Auto-Stream Download",
    instantDownDesc: "Forcing instant package delivery, triggering automatic download triggers directly.",
    autoStart: "Instant Download Trigger",
    autoStartDesc: "Automatically starts download as soon as link resolution completes successfully.",
    statsTitle: "Hyper Speed Engine Telemetry",
    historyTitle: "Resolved Downloads History",
    clearHistory: "Clear Feed",
    realtimeSpeed: "Realtime Engine Speed",
    remTime: "Estimated Remaining Time",
    elapsed: "Elapsed",
    fileSizeLabel: "Scraped File Weight",
    closeBtn: "Close Active Panel",
    downloadStartSuccess: "Direct download triggered into browser stream pipeline successfully!",
    errorPre: "Engine Alert",
    howItWorks: "How High-Speed Bypassing Works",
    howItWorks1: "Server-side bypass agent requests the official MediaFire content registry without local tracker headers.",
    howItWorks2: "Resolvers crawl the primary download anchoring trees on-demand to decrypt hidden direct links.",
    howItWorks3: "Direct stream link is piped instantly to your web UI bypassing redundant page ads and waiting counters.",
    demoMode: "Simulation Engine",
    demoModeDesc: "Simulates direct downloads for quick testing and UI capability evaluation.",
    simulateBtn: "Force Simulation Link"
  },
  hi: {
    title: "MediaFire 3D लिंक-बाईपास डाउनलोडर",
    subtitle: "बिना किसी एड्स और वेटिंग के MediaFire लिंक्स को डायरेक्ट हाई-स्पीड डाउनलोड में बदलें।",
    pasteLabel: "मीडियाफायर लिंक यहाँ पेस्ट करें",
    placeholder: "MediaFire लिंक यहाँ डालें (उदा. https://www.mediafire.com/file/...)",
    bypassBtn: "बाईपास और कन्वर्ट करें",
    bypassing: "लिंक बाईपास हो रहा है...",
    speedMode: "हाइपर 3D इंजन त्वरण",
    speedModeDesc: "मल्टी-थ्रेडेड टर्बो इंजन जो डाउनलोड स्पीड को कई गुना बढ़ा देता है।",
    instantDown: "ऑटो-स्टीम डाउनलोडर",
    instantDownDesc: "सीधे ब्राउज़र डाउनलोड ट्रिगर शुरू करता है, फाइल तुरंत प्राप्त करने के लिए।",
    autoStart: "ऑटो-स्टार्ट ट्रिगर",
    autoStartDesc: "जैसे ही लिंक कन्वर्ट होगा, डाउनलोड अपने आप बैकग्राउंड में शुरू हो जाएगा।",
    statsTitle: "हाइपर स्पीड इंजन टेलीमेट्री",
    historyTitle: "सफलतापूर्वक हल की गई फ़ाइलें",
    clearHistory: "सूची साफ करें",
    realtimeSpeed: "वास्तविक समय स्पीड चार्ट",
    remTime: "अनुमानित शेष समय",
    elapsed: "बिता हुआ समय",
    fileSizeLabel: "डिटेक्ट किया गया साइज़",
    closeBtn: "एक्टिव पैनल बंद करें",
    downloadStartSuccess: "डायरेक्ट डाउनलोड लिंक सफलतापूर्वक तैयार और ऑटो-ट्रिगर हो गया है!",
    errorPre: "सिस्टम त्रुटि",
    howItWorks: "बाईपास इंजन काम कैसे करता है?",
    howItWorks1: "हमारा सर्वर-साइड एजेंट बिना विज्ञापन या ट्रैकर के आधिकारिक मीडियाफ़ायर रजिस्ट्री से संपर्क करता है।",
    howItWorks2: "सिस्टम पेज एचटीएमएल को पार्स करके सीधा डाइरेक्ट डाउनलोड 'href' यूआरएल एंकर निकालता है।",
    howItWorks3: "विज्ञापन साइटों और प्रतीक्षा काउंटरों को छोड़ कर सीधा स्ट्रीम लिंक ब्राउज़र को स्वचालित रूप से भेज दिया जाता है।",
    demoMode: "सिमुलेशन टेस्ट इंजन",
    demoModeDesc: "त्वरित परीक्षण और सुंदर 3D इंटरफेस का अनुभव करने के लिए डाउनलोड का अनुकरण करें।",
    simulateBtn: "सॉफ्ट सिमुलेशन शुरू करें"
  }
};
